model:
  name: resnet50
  parameters:
    num_classes: 2
    weights: DEFAULT
training:
  batch_size: 20
  num_workers: 4
  learning_rate: 0.001
  max_epochs: 1000
  early_stopping_patience: 20
train_transforms:
- type: Resize
  size:
  - 256
  - 256
- type: ToTensor
- type: Lambda
  function: repeat_channels
- type: RandomHorizontalFlip
- type: RandomRotation
  degrees: 360
- type: ColorJitter
  brightness: 0.4
  contrast: 0.4
  saturation: 0.4
  hue: 0.2
- type: GaussianBlur
  kernel_size: 5
  sigma: 1.0
- type: Normalize
  mean: &id001
  - 0.5314157605171204
  - 0.49074479937553406
  - 0.3935178518295288
  std: &id002
  - 0.30881452560424805
  - 0.28827348351478577
  - 0.2249414622783661
val_transforms:
- type: Resize
  size:
  - 256
  - 256
- type: ToTensor
- type: Lambda
  function: repeat_channels
- type: RandomHorizontalFlip
- type: RandomRotation
  degrees: 360
- type: Normalize
  mean: *id001
  std: *id002
test_transforms:
- type: Resize
  size:
  - 256
  - 256
- type: ToTensor
- type: Lambda
  function: repeat_channels
- type: RandomHorizontalFlip
- type: RandomRotation
  degrees: 360
- type: Normalize
  mean: *id001
  std: *id002
optimizer:
  type: Adam
  params:
    lr: 0.001
scheduler:
  type: ReduceLROnPlateau
  params:
    mode: min
    factor: 0.1
    patience: 10
    min_lr: 1.0e-08
