model:
  name: ResNetModel
  parameters:
    model_name: resnet50
    num_classes: 2
    weights: DEFAULT
training:
  batch_size: 10
  num_workers: 6
  learning_rate: 0.001
  max_epochs: 1000
  early_stopping_patience: 100
train_transforms:
- type: Resize
  size:
  - 256
  - 256
- type: ToTensor
- type: Lambda
  function: repeat_channels
- type: RandomHorizontalFlip
  p: 0.5
- type: RandomVerticalFlip
  p: 0.5
- type: RandomRotation
  degrees: 360
  p: 0.5
- type: RandomPerspective
  distortion_scale: 0.5
  p: 0.5
- type: RandomAffine
  degrees: 360
  translate: 0.2
  scale: 0.2
  shear: 10
  p: 0.5
- type: ColorJitter
  brightness: 0.3
  contrast: 0.3
  saturation: 0.3
  hue: 0.2
  p: 0.5
- type: GaussianBlur
  kernel_size: 5
  sigma: 1.0
  p: 0.5
- type: Normalize
  mean: &id001
  - 0.5314157605171204
  - 0.49074479937553406
  - 0.3935178518295288
  std: &id002
  - 0.30881452560424805
  - 0.28827348351478577
  - 0.2249414622783661
val_transforms:
- type: Resize
  size:
  - 256
  - 256
- type: ToTensor
- type: Lambda
  function: repeat_channels
- type: Normalize
  mean: *id001
  std: *id002
test_transforms:
- type: Resize
  size:
  - 256
  - 256
- type: ToTensor
- type: Lambda
  function: repeat_channels
- type: Normalize
  mean: *id001
  std: *id002
optimizer:
  type: AdamW
  params:
    lr: 5.0e-05
    weight_decay: 0.0001
scheduler:
  type: ReduceLROnPlateau
  params:
    mode: min
    factor: 0.1
    patience: 10
    min_lr: 1.0e-08
