model:
  name: CNNModelForCIFAR10
  parameters:
    num_classes: 2
    input_size: 256
    hidden_layers:
    - 512
    - 256
    - 128
    - 64
    activation_function: LeakyReLU
    dropout_rate: 0.1
    num_pool_layers: 3
    conv_start_size: 64
training:
  batch_size: 100
  num_workers: 4
  learning_rate: 0.001
  max_epochs: 1000
  early_stopping_patience: 20
transforms:
- type: Resize
  size:
  - 32
  - 32
- type: RandomCrop
  size:
  - 32
  - 32
  padding: 4
- type: ToTensor
- type: Lambda
  function: repeat_channels
- type: RandomHorizontalFlip
- type: RandomRotation
  degrees: 30
- type: ColorJitter
  brightness: 0.2
  contrast: 0.2
  saturation: 0.2
  hue: 0.1
- type: Normalize
  mean:
  - 0.4914
  - 0.4822
  - 0.4465
  std:
  - 0.247
  - 0.2435
  - 0.2616
optimizer:
  type: Adam
  params:
    lr: 0.001
scheduler:
  type: ReduceLROnPlateau
  params:
    mode: min
    factor: 0.1
    patience: 10
    min_lr: 1.0e-08
